[package]
name = "nexus-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
axelar-wasm-std = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
connection-router = { workspace = true, features = ["library"] }
axelar-wasm-std-derive = { workspace = true }
cw-storage-plus = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }
report = { workspace = true }
mockall = "0.11.4"
